### PR TITLE
Added Mobile menu

### PR DESCRIPTION
**Pull request by HanningtoneM**
- Used basic JavaScript syntax.
- Used JavaScript to manipulate DOM elements.
- Used JavaScript events.
Made the mobile menu to perform the following functions;
- When the user clicks (or taps) the hamburger button, the mobile menu appears.
- When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @HanningtoneM, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ Good PR Title and Description
✔️ All linters are passing
✔️ Professional Readme

## Required 

- [x] Kindly Update Your Readme with a description of the project and collaborator details.

- [x] Kindly fix the hamburger menu button. Right now it is not working as shown in the video attached. It is throwing errors and the javascript file is not loading due to some errors.

https://user-images.githubusercontent.com/70269507/167466504-0c9b3dee-1472-4a15-9f1f-e8610a829d05.mov

- As the hamburger button is not working I couldn't check the following:-
- [x] When the user clicks (or taps) the hamburger button, the mobile menu appears.
- [x] When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- [x] When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.
- [x] When the user clicks (or taps) any option of the mobile menu, the mobile menu disappears.
- [x] The hamburger menu follows the design from the chosen template in Figma (e.g., font, colours, images, tests, margins).

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by HanningtoneM** [comment]
@sja-thedude my hamburger menu is working on my side perfectly I don't understand the issue. everything on my side is running perfectly please check your end and get back to me so that I know what  I can submit

**Comment by sja-thedude** [comment]
> @sja-thedude my hamburger menu is working on my side perfectly I don't understand the issue. everything on my side is running perfectly please check your end and get back to me so that I know what  I can submit

@HanningtoneM have you tried running on chrome? Maybe you have to fix the issue on chrome?

**Comment by HanningtoneM** [comment]
@sja-thedude yes i have run it on chrome everything is working perfectly on my end should I request a second opinion?
because I have no error of that kind I have checked my work more than 5 times

**Comment by sja-thedude** [comment]
@HanningtoneM Yes you can ask for second opinion. Or I can leave a message for the next CR if you want!

**Comment by HanningtoneM** [comment]
@sja-thedude the Github pages live demo link is showing that it works correctly

**Comment by sja-thedude** [comment]
> @sja-thedude the Github pages live demo link is showing that it works correctly

@HanningtoneM Yes, it is working correctly on Github pages. You can request another review.

**Review by danmainah — APPROVED** [review]
Hi @team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design
✔️  Good PR and Description
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
